---
# Manage Tool Shed Database

- name: Get current Tool Shed DB version
  command: "{{ galaxy_toolshed_venv_dir }}/bin/python {{ galaxy_toolshed_server_dir }}/scripts/manage_db.py -c {{ galaxy_toolshed_config_file }} db_version tool_shed chdir={{ galaxy_toolshed_server_dir }}"
  environment:
    GALAXY_EGGS_PATH: "{{ galaxy_toolshed_eggs_path | default(galaxy_toolshed_server_dir ~ '/eggs') }}"
  register: current_db_version
  changed_when: False
  failed_when: current_db_version.rc != 0 and 'migrate.exceptions.DatabaseNotControlledError' not in current_db_version.stderr

- name: Get maximum Tool Shed DB version
  command: "{{ galaxy_toolshed_venv_dir }}/bin/python {{ galaxy_toolshed_server_dir }}/scripts/manage_db.py -c {{ galaxy_toolshed_config_file }} version tool_shed chdir={{ galaxy_toolshed_server_dir }}"
  environment:
    GALAXY_EGGS_PATH: "{{ galaxy_toolshed_eggs_path | default(galaxy_toolshed_server_dir ~ '/eggs') }}"
  register: max_db_version
  changed_when: False

- name: Create Bootstrap User Info
  template: src=user_info.xml.j2 dest={{ galaxy_toolshed_server_dir }}/scripts/tool_shed/bootstrap_tool_shed/user_info.xml
  when: galaxy_toolshed_bootstrap

- name: Create Tool Shed DB
  command: "{{ galaxy_toolshed_venv_dir }}/bin/python {{ galaxy_toolshed_server_dir }}/scripts/create_db.py -c {{ galaxy_toolshed_config_file }} tool_shed chdir={{ galaxy_toolshed_server_dir }}"
  environment:
    GALAXY_EGGS_PATH: "{{ galaxy_toolshed_eggs_path | default(galaxy_toolshed_server_dir ~ '/eggs') }}"
  when: "'migrate.exceptions.DatabaseNotControlledError' in current_db_version.stderr and not galaxy_toolshed_bootstrap"

- name: Bootstrap Tool Shed DB
  command: "/bin/bash -c 'cd {{ galaxy_toolshed_server_dir }} && mkdir {{ galaxy_toolshed_config_dir }}/hgweb_config_dir/ && . {{ galaxy_toolshed_venv_dir }}/bin/activate && /bin/bash {{ galaxy_toolshed_server_dir }}/scripts/tool_shed/bootstrap_tool_shed/bootstrap_tool_shed.sh -bootstrap_from_tool_shed https://toolshed.g2.bx.psu.edu > /tmp/ts_bootstrap_output.log  || true '"
  environment:
    GALAXY_EGGS_PATH: "{{ galaxy_toolshed_eggs_path | default(galaxy_toolshed_server_dir ~ '/eggs') }}"
    TOOL_SHED_CONFIG_FILE: "{{ galaxy_toolshed_config_file }}"
  when: "'migrate.exceptions.DatabaseNotControlledError' in current_db_version.stderr and galaxy_toolshed_bootstrap"
  sudo: yes
  sudo_user: "{{ galaxy_user_name }}"

- name: Upgrade Tool Shed DB
  command: "{{ galaxy_toolshed_venv_dir }}/bin/python {{ galaxy_toolshed_server_dir }}/scripts/manage_db.py -c {{ galaxy_toolshed_config_file }} upgrade tool_shed chdir={{ galaxy_toolshed_server_dir }}"
  environment:
    GALAXY_EGGS_PATH: "{{ galaxy_toolshed_eggs_path | default(galaxy_toolshed_server_dir ~ '/eggs') }}"
  when: current_db_version.stdout != max_db_version.stdout and 'migrate.exceptions.DatabaseNotControlledError' not in current_db_version.stderr
