---
# main tasks file for galaxyproject.galaxy_toolshed

# Deploy a Galaxy Tool Shed server
#   https://wiki.galaxyproject.org/

- include_tasks: static_setup.yml
  when: galaxy_toolshed_manage_static_setup

- include_tasks: database.yml
  when: galaxy_toolshed_manage_database
