---
# Manage static Tool Shed configuration files

- name: Create Tool Shed config dir
  file:
    state: directory
    path: "{{ galaxy_toolshed_config_dir }}"

- name: Install additional Tool Shed config files (static)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ galaxy_toolshed_config_file_mode | default(omit) }}"
    backup: yes
  with_items: "{{ galaxy_toolshed_config_files }}"

- name: Install additional Tool Shed config files (template)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ galaxy_toolshed_config_file_mode | default(omit) }}"
    backup: yes
  with_items: "{{ galaxy_toolshed_config_templates }}"

- name: Create Tool Shed configuration file
  template:
    src: "{{ galaxy_toolshed_config_file_template }}"
    dest: "{{ galaxy_toolshed_config_file }}"
    mode: "{{ galaxy_toolshed_config_file_mode | default(omit) }}"
    backup: yes
  notify:
    - "{{ galaxy_toolshed_restart_handler_name | default('default restart galaxy tool shed handler') }}"
